import { StyleSheet, Platform, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'flex-start',
  },
  iPhoneX: {
    paddingBottom: height === 812 && Platform.OS === 'ios' ? 20 : 0,
  },
  bucketlistRow: {
    flex: 1,
    margin: 10,
  },
  image: {
    display: 'flex',
    resizeMode: 'cover',
    justifyContent: 'center',
    width: '100%',
    marginVertical: 10,
    backgroundColor: 'grey',
  },
  empty: {
    height: 40,
    margin: 20,
    fontSize: 20,
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#fff',
  },
  modal: {
    backgroundColor: '#f7f7f7',
    alignSelf: 'center',
  },
  input: {
    width: '100%',
    marginTop: -20,
  },
  inputStyle: {
    paddingBottom: 3,
    width: '100%',
  },
  otherField: {
    width: '100%',
    fontWeight: '500',
    marginTop: 20,
    marginBottom: 5,
  },
  dialog: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    width: '90%',
    marginLeft: 20,
    marginRight: 20,
  },
  profileAvatar: {
    flexBasis: '10%',
    maxWidth: 40,
  },
  displayName: {
    flexBasis: '90%',
    marginLeft: 10,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: 20,
    color: 'grey',
  },
  newBucketlist: {
    backgroundColor: '#f7f7f7',
    borderRadius: 5,
    paddingTop: 20,
    padding: 20,
    margin: 5,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    color: 'grey',
  },
  grid: {
    display: 'flex',
    flex: 1,
  },
  bucketlist: {
    backgroundColor: '#f7f7f7',
    borderRadius: 5,
    paddingTop: 20,
    paddingBottom: 10,
    marginHorizontal: 5,
    marginVertical: 2.5,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    height: 'auto',
    elevation: 1,
  },
  bucketlistHeader: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    width: '100%',
    paddingHorizontal: 20,
  },
  avatar: {
    display: 'flex',
    flexBasis: '10%',
    minWidth: 40,
    maxWidth: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#eee',
  },
  nameTime: {
    flexGrow: 1,
    marginLeft: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 40,
  },
  grey: {
    color: 'grey',
  },
  bucketlistBody: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    flexDirection: 'column',
    width: 'auto',
    borderRadius: 5,
    height: 'auto',
  },
  description: {
    width: '90%',
    marginVertical: 10,
    borderRadius: 5,
    marginHorizontal: 20,
  },
  blue: {
    color: '#00bcd4',
  },
  commentButton: {
    display: 'flex',
    fontSize: 12,
    color: 'grey',
  },
  likeButton: {
    display: 'flex',
    alignSelf: 'flex-start',
    fontSize: 12,
  },
  commentSection: {
    display: 'flex',
    flexDirection: 'column-reverse',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    backgroundColor: '#f7f7f7',
    width: '100%',
    paddingHorizontal: 20,
  },
  comment: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginTop: 5,
    padding: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
    backgroundColor: '#eee',
    maxWidth: '95%',
  },
  commentUser: {
    display: 'flex',
    fontSize: 11,
    color: '#00bcd4',
  },
  commentContent: {
    fontSize: 10,
    display: 'flex',
    color: 'grey',
    marginLeft: 5,
  },
  newComment: {
    width: '100%',
    height: 40,
    marginTop: 10,
    paddingHorizontal: 20,
    backgroundColor: '#f7f7f7',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  currentAvatar: {
    flexBasis: '10%',
    marginLeft: 0,
    maxWidth: 24,
    height: 24,
    borderRadius: 12,
  },
  inputText: {
    marginLeft: 10,
    fontSize: 12,
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: 'grey',
  },
  label: {
    display: 'flex',
    fontSize: 12,
    color: '#00bcd4',
  },
  value: {
    display: 'flex',
    flexBasis: '20%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  loadMore: {
    position: 'absolute',
    top: 70,
    display: 'flex',
    marginTop: 0,
    left: 0,
    right: 0,
    marginLeft: 'auto',
    marginRight: 'auto',
    width: 100,
    borderRadius: 24,
    zIndex: 3,
  },
  addNew: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    color: 'grey',
    margin: '0 auto',
    fontSize: 20,
    marginTop: '10vh',
  },
  here: {
    color: '#00bcd4',
  },
  progress: {
    position: 'absolute',
    top: 0,
    zIndex: 1000000,
  },
  likesComments: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: 'auto',
    paddingHorizontal: 10,
  },
  iconStyle: {
    display: 'flex',
    height: 'auto',
  },
  iconsStyle: {
    display: 'flex',
    height: 18,
    width: 18,
  },
  span: {
    display: 'flex',
    width: 20,
    fontSize: 12,
    marginLeft: 5,
    color: 'grey',
  },
  text: {
    display: 'flex',
  },
  bigIcon: {
    fontSize: 200,
    marginBottom: 100,
  },
  chip: {
    display: 'flex',
    marginRight: 5,
  },
  tagList: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 5,
    paddingHorizontal: 20,
  },
  hashTag: {
    display: 'flex',
    height: 20,
    lineHeight: 20,
    color: '#00bcd4',
    fontSize: 12,
    marginRight: 5,
  },
  leftHeaderContent: {
    color: 'grey',
    fontSize: 12,
    fontWeight: 'bold',
    height: 12,
  },
  rightHeaderContent: {
    color: 'grey',
    fontSize: 12,
    height: 12,
  },
  titleIcon: {
    fontSize: 12,
    marginRight: 5,
    color: '#00bcd4',
    display: 'flex',
    marginVertical: 0,
    paddingVertical: 0,
  },
  lifegoBlue: {
    color: '#00bcd4',
  },
  shortInputs: {
    display: 'flex',
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: -20,
  },
  shortInput: {
    width: '30%',
  },
  shortInputStyle: {
    paddingBottom: 3,
    width: '100%',
  },
  thirty: {
    width: '100%',
  },
  tags: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  headDetails: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginVertical: 5,
    height: 30,
  },
  listView: {
    marginTop: 2.5,
  },
});
