import {
  StyleSheet,
  Platform,
  Dimensions,
} from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignContent: 'stretch',
    backgroundColor: '#fff',
    height: '100%',
    width,
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Platform.OS === 'ios' ? '#00bcd4' : 'grey',
    display: 'flex',
    textAlign: Platform.OS === 'ios' ? 'center' : 'left',
    paddingVertical: 10,
    paddingHorizontal: 5,
  },
  hr: {
    borderBottomColor: Platform.OS === 'android' ? 'grey' : '#00bcd4',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  input: {
    display: 'flex',
    color: 'grey',
    fontWeight: '600',
    fontSize: Platform.OS === 'ios' ? 12 : 16,
    marginLeft: 0,
    marginRight: 0,
    marginBottom: 3,
    marginTop: 2,
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderRadius: Platform.OS === 'ios' ? 5 : 0,
    backgroundColor: Platform.OS === 'ios' ? '#f9f9f9' : 'transparent',
  },
  category: {
    display: 'flex',
    marginLeft: 0,
    marginRight: 0,
    marginBottom: 3,
    marginTop: 2,
    padding: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderBottomColor: '#00bcd4',
  },
  categoryAndroid: {
    borderWidth: 1 + StyleSheet.hairlineWidth,
    borderBottomColor: '#00bcd4',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: 'transparent',
    height: 30,
  },
  buttonText: {
    display: 'flex',
    fontSize: Platform.OS === 'ios' ? 12 : 16,
    fontWeight: '600',
    color: Platform.OS === 'ios' ? '#fff' : '#00bcd4',
    backgroundColor: 'transparent',
  },
  cancelButtonText: {
    color: Platform.OS === 'ios' ? '#fff' : 'grey',
  },
  button: {
    display: 'flex',
    borderRadius: 5,
    flexDirection: 'row',
    backgroundColor: Platform.OS === 'ios' ? '#00bcd4' : 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginLeft: 5,
  },
  cancelButton: {
    display: 'flex',
    backgroundColor: Platform.OS === 'ios' ? 'grey' : 'transparent',
  },
  buttons: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 25,
    marginBottom: 5,
  },
  divider: {
    display: 'flex',
    backgroundColor: '#00bcd4',
  },
  grey: {
    display: 'flex',
    color: Platform.OS === 'ios' ? 'grey' : '#00bcd4',
    fontSize: 16,
    paddingHorizontal: 5,
    marginTop: 10,
  },
});
