import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    display: 'flex',
    position: 'absolute',
    left: 10,
    right: 10,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 5,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#eee',
    backgroundColor: '#fff',
    paddingVertical: 10,
    overflow: 'hidden',
  },
  label: {
    fontSize: 16,
    color: 'red',
    display: 'flex',
    textAlign: 'center',
  },
  button: {
    display: 'flex',
    flexDirection: 'row',
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    borderColor: '#eee',
    backgroundColor: '#fcfcfc',
    borderWidth: StyleSheet.hairlineWidth,
    minWidth: 100,
  },
  text: {
    fontSize: 16,
    color: '#00bcd4',
    display: 'flex',
    textAlign: 'left',
    paddingVertical: 10,
  },
  buttonGroup: {
    width: '100%',
    marginTop: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
});
