import { StyleSheet, Platform, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');
const scaleX = Platform.OS === 'ios' ? 0.5 : 1;
const scaleY = scaleX;

export default StyleSheet.create({
  container: {
    display: 'flex',
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'flex-start',
    paddingBottom: height === 814 && Platform.OS === 'ios' ? 20 : 0,
    width: '100%',
  },
  body: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    backgroundColor: '#fff',
  },
  switchRow: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginVertical: 5,
  },
  input: {
    display: 'flex',
    color: '#666',
    fontSize: 16,
    marginHorizontal: 15,
    marginVertical: 2,
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderRadius: Platform.OS === 'ios' ? 5 : 0,
    backgroundColor: Platform.OS === 'ios' ? '#f9f9f9' : 'transparent',
  },
  switchText: {
    display: 'flex',
    color: '#666',
    fontSize: 16,
  },
  switch: {
    display: 'flex',
    backgroundColor: 'transparent',
    transform: [{ scaleX }, { scaleY }],
  },
  button: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f7f7f7',
    padding: 5,
    borderRadius: 10,
    width: 200,
    marginHorizontal: '25%',
    marginVertical: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#00bcd4',
  },
  saveButton: {
    display: 'flex',
    borderRadius: 5,
    flexDirection: 'row',
    backgroundColor: Platform.OS === 'ios' ? '#00bcd4' : 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginLeft: 5,
  },
  saveButtons: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    height: 40,
    backgroundColor: '#fff',
    paddingHorizontal: 20,
  },
  buttons: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    borderRadius: 10,
    margin: 10,
    paddingHorizontal: 10,
  },
  buttonText: {
    display: 'flex',
    textAlign: 'left',
    fontSize: 16,
    color: '#666',
    fontWeight: 'bold',
  },
  inputText: {
    display: 'flex',
    color: Platform.OS === 'ios' ? 'grey' : '#00bcd4',
    fontSize: 16,
    paddingHorizontal: 5,
    marginTop: 10,
    marginHorizontal: 15,
  },
  cancelButton: {
    display: 'flex',
    backgroundColor: Platform.OS === 'ios' ? 'grey' : 'transparent',
  },
  saveButtonText: {
    display: 'flex',
    fontSize: 16,
    fontWeight: '600',
    color: Platform.OS === 'ios' ? '#fff' : '#00bcd4',
    backgroundColor: 'transparent',
  },
  cancelButtonText: {
    color: Platform.OS === 'ios' ? '#fff' : 'grey',
  },
});
