import { StyleSheet, Platform, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    display: 'flex',
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'flex-start',
    paddingBottom: height === 812 && Platform.OS === 'ios' ? 20 : 0,
    width: '100%',
  },
  profileWrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingTop: 20,
    paddingBottom: 2,
    zIndex: 5,
  },
  profilePicWrapper: {
    display: 'flex',
    borderWidth: 2,
    borderColor: '#f7f7f7',
    overflow: 'hidden',
    marginBottom: 15,
  },
  profilePic: {
    flex: 1,
    height: null,
    width: null,
  },
  profileName: {
    display: 'flex',
    color: 'grey',
    fontSize: 24,
    marginVertical: 5,
  },
  profileEmail: {
    display: 'flex',
    color: 'grey',
    fontSize: 14,
    marginVertical: 5,
  },
  profileAction: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    height: 30,
    width: 200,
    backgroundColor: '#f7f7f7',
    marginVertical: 5,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#f7f7f7',
  },
  profileActionText: {
    display: 'flex',
    color: 'grey',
    fontWeight: 'bold',
  },
  profileStats: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 50,
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#f7f7f7',
    backgroundColor: '#f7f7f7',
    marginHorizontal: 10,
    marginTop: 15,
  },
  stat: {
    display: 'flex',
    flexBasis: '50%',
    alignItems: 'center',
    height: '100%',
  },
  statWrapper: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statCount: {
    display: 'flex',
    textAlign: 'center',
    width: '100%',
    color: 'grey',
    fontSize: 20,
  },
  statCountActive: {
    fontWeight: 'bold',
    color: '#00bcd4',
  },
  statLabel: {
    display: 'flex',
    textAlign: 'center',
    width: '100%',
    color: 'grey',
    fontSize: 14,
  },
  statLabelActive: {
    fontWeight: 'bold',
    color: '#00bcd4',
  },
  profileBody: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    marginHorizontal: 10,
    marginVertical: 20,
    borderRadius: 5,
    paddingVertical: 10,
    zIndex: 10,
  },
  person: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 60,
    marginHorizontal: 20,
    padding: 2,
    borderBottomColor: '#fff',
  },
  lastPerson: {
    borderBottomWidth: 0,
  },
  personPic: {
    display: 'flex',
    height: 40,
    width: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#ccc',
  },
  personName: {
    display: 'flex',
    color: 'grey',
    flexGrow: 1,
    fontSize: 14,
    fontWeight: 'bold',
    marginHorizontal: 10,
  },
  personAction: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    width: 70,
    height: 25,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#00bcd4',
  },
  removeAction: {
    backgroundColor: '#00bcd4',
  },
  actionText: {
    display: 'flex',
    textAlign: 'center',
    fontSize: 14,
    color: '#00bcd4',
    fontWeight: 'bold',
  },
  removeActionText: {
    color: '#fff',
  },
  noPeople: {
    display: 'flex',
    marginVertical: 20,
    color: 'grey',
    width: '100%',
    textAlign: 'center',
    fontSize: 14,
  },
  list: {
    flex: 1,
    overflow: 'hidden',
    padding: 0,
    marginVertical: 10,
  },
  borderRadius: {
    borderRadius: 5,
    overflow: 'hidden',
  },
  scrollView: {
    overflow: 'scroll',
    paddingVertical: 10,
    borderRadius: 5,
    backgroundColor: '#fff',
  },
  input: {
    display: 'flex',
    color: 'grey',
    fontSize: 14,
    marginHorizontal: 0,
    marginVertical: 2,
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderRadius: Platform.OS === 'ios' ? 5 : 0,
    backgroundColor: Platform.OS === 'ios' ? '#f9f9f9' : 'transparent',
  },
  grey: {
    display: 'flex',
    color: Platform.OS === 'ios' ? 'grey' : '#00bcd4',
    fontSize: 14,
    paddingHorizontal: 5,
    marginTop: 10,
  },
  buttonText: {
    display: 'flex',
    fontSize: 14,
    fontWeight: '600',
    color: Platform.OS === 'ios' ? '#fff' : '#00bcd4',
    backgroundColor: 'transparent',
  },
  cancelButtonText: {
    color: Platform.OS === 'android' ? 'grey' : '#00bcd4',
  },
  button: {
    display: 'flex',
    borderRadius: 5,
    flexDirection: 'row',
    backgroundColor: Platform.OS === 'ios' ? '#00bcd4' : 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
    margin: 5,
  },
  cancelButton: {
    display: 'flex',
    backgroundColor: 'transparent',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Platform.OS === 'ios' ? '#00bcd4' : 'transparent',
  },
  buttons: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: 5,
  },
  title: {
    fontSize: 14,
    fontWeight: 'bold',
    color: Platform.OS === 'ios' ? '#00bcd4' : 'grey',
    display: 'flex',
    textAlign: Platform.OS === 'ios' ? 'center' : 'left',
    paddingVertical: 10,
    paddingHorizontal: 5,
  },
  uploading: {
    fontSize: 14,
    color: '#fff',
    display: 'flex',
    textAlign: 'center',
    marginVertical: 10,
  },
  hr: {
    display: 'flex',
    borderBottomColor: Platform.OS === 'android' ? '#f7f7f7' : '#00bcd4',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  activity: {
    display: 'flex',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: '30%',
  },
  editProfileView: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    overflow: 'hidden',
    zIndex: 10,
    width: '100%',
    paddingHorizontal: 10,
  },
  photoButton: {
    backgroundColor: 'transparent',
    height: 24,
    width: null,
    paddingHorizontal: 10,
    marginVertical: 0,
  },
  photoButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'normal',
  },
  editForm: {
    flex: 1,
    width: '100%',
    padding: 10,
    backgroundColor: '#fff',
  },
  profileView: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  fullWidth: {
    width: '100%',
  },
  profileBodyStyle: {
    width: '100%',
    flexGrow: 1,
  },
  formBody: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
  },
});
