export default [
  'Art & Design',
  'Auto & Vehicles',
  'Books',
  'Business',
  'Dating',
  'Education',
  'Entertainment',
  'Events',
  'Finance',
  'Food & Drink',
  'Health & Fitness',
  'House & Home',
  'Music',
  'Photography',
  'Shopping',
  'Social',
  'Sports',
  'Travel & Local',
  'Adventure',
  'Other',
];
