import { StyleSheet, Platform } from 'react-native';

export default { localStyles: StyleSheet.create({
  row: {
    display: 'flex',
    backgroundColor: 'transparent',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  container: {
    display: 'flex',
    backgroundColor: 'rgba(255, 255, 255,1)',
    borderWidth: 0,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
  },
  bucketlist: {
    backgroundColor: '#f7f7f7',
    borderRadius: 5,
    paddingTop: 20,
    paddingBottom: 10,
    borderWidth: 0,
    margin: 5,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    height: 'auto',
    elevation: 1,
  },
  swipeout: {
    display: 'flex',
    backgroundColor: 'transparent',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
    alignItems: 'center',
  },
  title: {
    color: '#00bcd4',
    fontSize: 14,
  },
  divider: {
    backgroundColor: '#00bcd4',
  },
  label: {
    padding: 5,
    color: '#00bcd4',
    fontSize: 20,
    fontWeight: '600',
  },
  description: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: 5,
    color: 'grey',
    fontSize: 12,
  },
  drag: {
    display: 'flex',
    flexBasis: '5%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  text: {
    display: 'flex',
    flexDirection: 'row',
    lineHeight: 5,
    color: 'grey',
    fontWeight: '600',
  },
  modal: {
    backgroundColor: 'transparent',
    marginTop: 50,
    position: 'absolute',
    alignSelf: 'center',
    width: '90%',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignContent: 'center',
    backgroundColor: '#f7f7f7',
    borderRadius: 5,
  },
  detailRow: {
    flexBasis: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    height: '20%',
    marginTop: 5,
    marginBottom: 5,
  },
  property: {
    borderRadius: 5,
    flexDirection: 'row',
    flexBasis: '80%',
    fontWeight: '600',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    padding: 5,
  },
  propertyValue: {
    flexBasis: '80%',
  },
  button: {
    marginTop: 5,
    borderRadius: 5,
    flexDirection: 'row',
    flexBasis: '45%',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
    backgroundColor: '#666',
  },
  handleTouch: {
    display: 'flex',
    flexBasis: '95%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  done: {
    width: 50,
    height: 50,
    flexBasis: '15%',
  },
  iconStyles: {
    display: 'flex',
    marginTop: '15%',
  },
  checkbox: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    marginRight: 5,
    marginVertical: 0,
    marginTop: Platform.OS === 'android' ? '5%' : '4%',
  },
}),
baseStyles: StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignSelf: 'stretch',
    padding: 10,
    backgroundColor: 'transparent',
    justifyContent: 'space-between',
  },
  doneButton: {
    padding: 5,
    borderRadius: 5,
    backgroundColor: '#eaeaea',
    alignItems: 'center',
    justifyContent: 'center',
  },
  text: {
    fontSize: 18,
    fontWeight: '600',
    color: '#aaaaaa',
    paddingTop: 10,
  },
}),
};
